In [2]:
import numpy as np

In [3]:
zero = np.zeros(7)
zero

array([0., 0., 0., 0., 0., 0., 0.])

In [4]:
type(zero)

numpy.ndarray

In [5]:
one = np.ones(10)

In [6]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
e = np.empty(5)

In [8]:
e

array([2.12199579e-314, 7.74528464e-312, 3.49798477e-321, 3.79442416e-321,
       3.69126375e-317])

In [9]:
ran = np.linspace(2,100,50)

In [10]:
ran

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
        24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
        46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,
        68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,
        90.,  92.,  94.,  96.,  98., 100.])

In [11]:
type(ran)

numpy.ndarray

In [12]:
list = [[1,2,3,4],[1,2,3,4]]

In [13]:
arr = np.array(list)

In [14]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [15]:
arr.shape

(2, 4)

In [16]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [17]:
?arr

Type:        ndarray
String form:
[[1 2 3 4]
 [1 2 3 4]]
Length:      2
File:        c:\users\absar\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtyp